### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by FloatingMaple** [XGFan/intellij-notes#1]
老哥 这个怎么安装哇。
在plugin里面直接安装压缩包不成功，Plugin 'notes' is incompatible with this installation。IDEA2020.1

**Comment by XGFan** [comment]
你试试最新的build，下载的zip包可能是重复压缩的，需要解压一次。
https://github.com/XGFan/intellij-notes/runs/980725539

**Comment by FloatingMaple** [comment]
emmmm 能详细讲下吗 没搞过这种。我尝试把代码down下来想自己打包结果一直卡在idealc-latest-eap-snapsh

**Comment by XGFan** [comment]
自己build的话，会下载一个idea community版本，所以会比较慢。
你看看这个Github Action的artifacts可不可以用。
https://github.com/XGFan/intellij-notes/actions/runs/214648186

**Comment by FloatingMaple** [comment]
ok了，win下还要手动设置一下快捷键，不然默认是 meta+shift+c 。谢谢老哥了
